# Generated by Django 3.2.8 on 2021-10-09 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Nombre (s)')),
                ('lastname', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('birthday', models.DateField(verbose_name='Fecha de nacimiento')),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Estatura (en metros)')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tienda')),
                ('type', models.CharField(choices=[('Abarrotes', 'Abarrotes'), ('Autoservicio', 'Autoservicio')], default='Autoservicio', max_length=15, verbose_name='Tipo de tienda')),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Producto')),
                ('description', models.TextField(max_length=600, verbose_name='Descripción del producto')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Precio')),
                ('foto', models.ImageField(null=True, upload_to='imgProducts', verbose_name='Agregar imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Seleccione la categoria del producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Distinguido', 'Distinguido'), ('Miembro', 'Miembro')], max_length=30, verbose_name='Tipo de cliente')),
                ('member', models.BooleanField(default=False, verbose_name='¿Es mienbro?')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person', verbose_name='Persona')),
                ('Store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
