# Generated by Django 3.2.8 on 2021-10-13 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del producto')),
                ('description', models.TextField(max_length=1000, verbose_name='Descrionción del producto')),
                ('foto', models.ImageField(null=True, upload_to='inventario', verbose_name='Seleccione una imagen')),
            ],
            options={
                'verbose_name': 'Producto a inventariar',
                'verbose_name_plural': 'Productos a inventriar',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIngreso', models.DateTimeField(verbose_name='Fecha y hora de ingreso')),
                ('perecedero', models.BooleanField(default=False, verbose_name='¿Es perecedero?')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.producto', verbose_name='Seleccione el producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
            },
        ),
    ]
